server:
  port: 8082
spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
      host: 192.168.20.196
      database: 0
  sso:
    sso-url: http://192.168.80.128:8099/sso
    exclude-path:
#logging:
#  level:
#    com.oliver: debug